### ISSUE TITLE
Uploading Archive stuck at "Verifying assets with the iTunes Store" stage with framework

### ISSUE THREAD

**Issue by zwang** [NeoTeo/SwiftGMP#12]
Hi Teo, 

Thank you for creating this library. I am using this in my project and finding it very neat and works well. 

I got a problem when I am trying to upload my app to iTunes store for testing. Basically I got stuck at this screen:

![screen shot 2017-07-28 at 12 57 43 am](https://user-images.githubusercontent.com/1171212/28708109-d4ff18a0-732f-11e7-82ed-9e674eea93ea.png)

I create a simple app just for testing with SwiftGMP, I tried to upload the app via Xcode or via Application Loader, both resulting stuck at "Verifying assets with the iTunes Store" stage.

If I remove the library as a dependency, I can successfully upload the app to iTunes connect. 

The testing app is created here: https://github.com/zwang/TestFactorize

Thank you in advance for your help. Have a great day. 

Zhao

**Comment by twodayslate** [comment]
I couldn't upload either and I thought it was a Carthage issue

-Zac

**Comment by zwang** [comment]
@twodayslate do you have a work around to resolve this? Or do you have more information about Carthage related to this problem? Thanks.

I tried to compile source by forking this one https://github.com/gugu/libgmp-ios, but it seems not that easy for me. :(

**Comment by zwang** [comment]
@twodayslate by any chance did you resolve the uploading issue? if so, do you mind sharing your solution? I will really appreciate your help!

**Comment by twodayslate** [comment]
No I couldn't figure it out

-Zac

**Comment by NeoTeo** [comment]
Have you tried disabling the the "include bitcode" option?

**Comment by zwang** [comment]
@NeoTeo Sorry, has been busy, forgot to check back. 

Yeah, to make things works, I figured out I had to disabling the "include bitcode" option. Then it finally works.

Thanks a lot for the lib and the help.

**Comment by zwang** [comment]
@twodayslate I see. Thanks for the help all the same.  Like @NeoTeo said, uncheck "Include bitcode" is the solution for now. Although later I might need to figure out how to make "include bitcode" works. 

Hopefully I can figure it out...
