### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by twodayslate** [NeoTeo/SwiftGMP#3]
The readme could use some improvements. 
- [x] Basic usage instructions
- [x] Instruction on how to create libgmp.a among other things in the [GMPLib folder](../GMPLib/) to assist with future updates
- [x] Mention GMP's license and update own license to reflect this  

>  Since version 6, GMP is distributed under the dual licenses, **GNU LGPL v3** and **GNU GPL v2**. These licenses make the library free to use, share, and improve, and allow you to pass on the result. The GNU licenses give freedoms, but also set firm restrictions on the use with non-free programs.
- [x] Carthage install instructions to help avoid [this](http://stackoverflow.com/questions/38987188/swift3-framework-module-is-empty).

I can do most of this except the GMPLib folder stuff. Let me know what you need help with and what you want me to submit a PR for.

**Comment by NeoTeo** [comment]
Absolutely. Now that the number of users is > 1 it makes sense to have a friendly readme. 

Making the libgmp.a was a massive pain and I've turned it into a script [here](https://github.com/NeoTeo/gmp-ios-builder) that could be helpful to users. The Carthage instructions should also be a simple copy from my other related projects (such as the SwiftBase58 that solved your problem earlier). 

As with the other stuff I don't mind doing it, but I'm fairly busy at the moment so I'll try and steal some time as I can.

**Comment by NeoTeo** [comment]
Good stuff! Who knows, we might even get > 2 users.

**Comment by twodayslate** [comment]
Getting listed [here](https://gmplib.org/manual/Language-Bindings.html#Language-Bindings) might help!
