### ISSUE TITLE
Swift3 branch as default branch

### ISSUE THREAD

**Issue by twodayslate** [NeoTeo/SwiftGMP#7]
With the release of Xcode 8 the `swift3` branch should be the default branch. Current `master` branch can be moved to a `swift2` or `swift2-legacy` branch. Also might as well update gmp to 6.1.1 since [gmp-ios-builder](https://github.com/NeoTeo/gmp-ios-builder) was just updated.

**Comment by NeoTeo** [comment]
- swift3 branch is now master
- old master is now swift2
- GMP libraries have been updated to 6.1.1
