### ISSUE TITLE
Update release

### ISSUE THREAD

**Issue by twodayslate** [NeoTeo/SwiftGMP#8]
`carthage update` is pulling the v0.4.3 release file which is out of date

**Comment by NeoTeo** [comment]
Yeah, that's a bug/feature of Carthage that when you don't specify the branch in your Cartfile, as in: 
`github "NeoTeo/SwiftGMP" "master"`
then it doesn't pull the head but the latest tag. :/ 
I'll tag the current head, but to avoid this for every change in head you should probably add "master" to your Cartfile (and I'll change the readme to reflect this).

**Comment by twodayslate** [comment]
Ah. Thanks!
